=== uo281835/SEW/F1Desktop/xml/circuito.dtd
<!ELEMENT circuito (longitud, anchura, fechaCarrera, horaCarrera, localidad, pais, referencias, fotografias, videos, salida, tramos)>

<!ELEMENT longitud (#PCDATA)>

<!ELEMENT anchura (#PCDATA)>

<!ELEMENT fechaCarrera (dia, mes, year)>
<!ELEMENT dia (#PCDATA)>
<!ELEMENT mes (#PCDATA)>
<!ELEMENT year (#PCDATA)>

<!ELEMENT horaCarrera (hora, minuto, segundo)>
<!ELEMENT hora (#PCDATA)>
<!ELEMENT minuto(#PCDATA)>
<!ELEMENT segundo (#PCDATA)>

<!ELEMENT localidad (#PCDATA)>

<!ELEMENT pais (#PCDATA)>

<!ELEMENT referencias (referencia, referencia, referencia, referencia*)>
<!ELEMENT referencia (#PCDATA)>

<!ELEMENT fotografias (fotografia, fotografia?,fotografia?,fotografia?,fotografia?)>
<!ELEMENT fotografia (#PCDATA)>

<!ELEMENT videos (video?, video?, video?)>
<!ELEMENT video (#PCDATA)>

<!ELEMENT salida (coordenadas)>

<!ELEMENT coordenadas (longitud, latitud, altura)>
<!ELEMENT longitud (#PCDATA)>
<!ELEMENT latitud(#PCDATA)>
<!ELEMENT altura (#PCDATA)>

<!ELEMENT tramos (tramo*)>
<!ELEMENT tramo (punto, distancia, numeroSector)>
<!ELEMENT punto (coordenadas)>
<!ELEMENT distancia (#PCDATA)>
<!ELEMENT numeroSector (#PCDATA)>


<!ATTLIST circuito nombre CDATA #REQUIRED>
<!ATTLIST localidad nombre CDATA #REQUIRED>
<!ATTLIST fotografia titulo CDATA #REQUIRED>
<!ATTLIST video titulo CDATA #REQUIRED>
<!ATTLIST referencia titular CDATA #REQUIRED>

=== uo281835/SEW/F1Desktop/xml/circuito.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE circuito SYSTEM "circuito.dtd">
<circuito nombre="Suzuka">
    <longitud>5807 km</longitud>
    <anchura>12 m</anchura>
    <fechaCarrera>
        <dia>7</dia>
        <mes>4</mes>
        <year>2024</year>
    </fechaCarrera>
    <horaCarrera>
        <hora>7</hora>
        <minuto>0</minuto>
        <segundo>0</segundo>
    </horaCarrera>
    <localidad> Suzuka </localidad>
    <pais> Japón </pais>
    <referencias>
        <referencia titular="Artículo sobre la carrera"> https://www.dazn.com/es-ES/news/motor/gp-japon-f1-suzuka-fecha-hora-canal-tv-donde-ver-online-gran-premio-mundial-formula-1/b2tcqfzf8g3g1j6wid17w04pi </referencia>
        <referencia titular="Artículo de la wikipedia sobre el circuito"> https://es.wikipedia.org/wiki/Circuito_de_Suzuka</referencia>
        <referencia titular="Artículo de la wikipedia sobre la carrera"> https://es.wikipedia.org/wiki/Gran_Premio_de_Jap%C3%B3n</referencia>
    </referencias>
    <fotografias>
        <fotografia titulo="foto1"> multimedia/images/fotoCircuito1.png</fotografia>
        <fotografia titulo="foto2"> multimedia/images/fotoCircuito2.png</fotografia>
        <fotografia titulo="foto3"> multimedia/images/fotoCircuito3.png</fotografia>
    </fotografias>
    <videos>
        <video titulo="video1"> multimedia/videos/videoCircuito1.mp4</video>
        <video titulo="video2"> multimedia/videos/videoCircuito2.mp4</video>
        <video titulo="video3"> multimedia/videos/videoCircuito3.mp4</video>
    </videos>
    <salida>
        <coordenadas>
            <longitud> 136º 31' 55''</longitud>
            <latitud> -34º 50' 36''</latitud>
            <altura> 52,31 m</altura>
        </coordenadas>
    </salida>
    <tramos>
        <tramo>
            <punto>
                <coordenadas>
                    <longitud> </longitud>
                    <latitud> </latitud>
                    <altura> </altura>
                </coordenadas>
            </punto>
            <distancia> </distancia>
            <numeroSector> </numeroSector>
        </tramo>
    </tramos>
</circuito>
